url: https://stb-gaming.github.io

sky-logo: /assets/img/favicon.png
permalink: pretty


collections:
  tv-guide:
    output: true
  box-office:
    output: true
  services:
    output: true
  programmes:
    output: true
    permalink: /tv-guide/:categories/:title
  channels:
    output: false
  categories:
    output: true
    permalink: /tv-guide/:title

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: tv-guide
    values:
      css:
      - sky-guide.css
      js:
      - sky-guide.js
  - scope:
      path: ""
      type: programmes
    values:
      css:
      - sky-tv.css
      js:
      - sky-tv.js

exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - LICENSE
  - plan.md
  - README.md
  - gulpfile.js
  - gemfiles
  - src
  - package.json
  - package-lock.json


plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-redirect-to
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mention
