url: https://stb-gaming.github.io

sky-logo: /assets/img/stb-logo.webp
permalink: pretty


collections:
  programmes:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: programmes
    values:
      css:
      - sky-tv.css
      js:
      - sky-tv.js

exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - LICENSE
  - plan.md
  - README.md
  - gulpfile.js
  - gemfiles
  - src
  - package.json
  - package-lock.json


plugins:
  - jekyll-redirect-from
